name: Assignment Autograding

on:
  push:
    branches:
      - main

jobs:
  grading:
    name: Check Assignment Progress
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    # Step 4: Install Dependencies
    - name: Install Dependencies
      run: |
        poetry install

    # Check Task 2: Poetry Setup
    - name: Task 2: Poetry Setup
      run: |
        if [ -f "pyproject.toml" ] && [ -f "poetry.lock" ]; then
          echo "Poetry setup verified."
        else
          echo "Error: Poetry files not found."
          exit 1
        fi

    # Check Task 3: Restructured Repository
    - name: Task 3: Restructure Repository
      run: |
        if [ -d "src/opticaldisp" ] && [ -f "src/opticaldisp/waveforms.py" ] && [ -f "src/opticaldisp/optical_signals.py" ] && [ -f "src/opticaldisp/dispersion.py" ]; then
          echo "Repository structure verified."
        else
          echo "Error: Restructured repository files missing."
          exit 1
        fi

    # Check Task 4: Linting with Ruff
    - name: Task 4: Linting with Ruff
      run: |
        poetry run ruff check . || exit 1

    # Check Task 5: LICENSE File
    - name: Task 5: LICENSE File
      run: |
        if [ -f "LICENSE" ]; then
          echo "LICENSE file verified."
        else
          echo "Error: LICENSE file not found."
          exit 1
        fi

    # Check Task 6: Unit Tests
    - name: Task 6: Unit Tests
      run: |
        if [ -d "tests" ] && [ -f "tests/tests.py" ]; then
          poetry run pytest tests || exit 1
        else
          echo "Error: Unit tests not implemented."
          exit 1
        fi

    # Check Task 7: Final Repository Structure
    - name: Task 7: Final Repository Structure
      run: |
        REQUIRED_FILES="README.md LICENSE src/opticaldisp/waveforms.py src/opticaldisp/optical_signals.py src/opticaldisp/dispersion.py tests/tests.py"
        for FILE in $REQUIRED_FILES; do
          if [ ! -f "$FILE" ]; then
            echo "Error: $FILE is missing."
            exit 1
          fi
        done
        echo "Final repository structure verified."

    # Provide progress in pull request
    - name: Update PR status
      if: success()
      run: echo "All tasks passed! 🎉"
